[package]
name = "dune"
version = "0.1.7"
authors = ["Adam McDaniel <adam.mcdaniel17@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "A shellğŸš by the beachğŸ–ï¸!!"
readme = "README.md"
documentation = "https://docs.rs/dune"
homepage = "https://github.com/adam-mcdaniel/dune"
repository = "https://github.com/adam-mcdaniel/dune"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "dunesh"
path = "src/bin.rs"

[dependencies]
clap = {version="3.0", features=["cargo"]}
json = "0.12.4"
terminal_size = "0.1.17"
textwrap = "0.14"
nom = "7.0"
detached-str = "0.1"
rand = "0.8"
ctrlc = "3.2"
common_macros = "0.1"
snailquote = "0.3"
rustyline = "9.1"
rustyline-derive = "0.6"
dirs = "4.0"
dunce = "1.0"
chess-engine = { version = "0.1.2", optional = true }

[dependencies.toml]
version = "0.5.8"
default-features = false

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "std"]

[dependencies.os_info]
version = "3.0"
default-features = false

[dependencies.prettytable-rs]
version = "0.8"
default-features = false
features = ["win_crlf"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "parser_benchmark"
harness = false
